version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(npm)
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(gha)
    pull-request-branch-name:
      separator: "/"
